### ISSUE TITLE
doesn't work without running pycsw_setup

### ISSUE THREAD

**Issue by rsignell-usgs** [axiom-data-science/docker-pycsw#7]
I have this `docker-compose.yml` set up for `pycsw`:
```
pycsw:
  image: axiom/docker-pycsw
  ports:
    - "8000:8000"
  container_name: pycsw
  volumes:
    - /opt/docker/pycsw/usgs-cmg.cfg:/opt/pycsw/default.cfg
    - /opt/docker/pycsw/force:/force
    - /opt/docker/pycsw/export:/export
    - /opt/docker/pycsw/store:/store
    - /opt/docker/pycsw/database:/database
    - /opt/docker/pycsw/cron.d:/etc/cron.d
```
When I run this for the first time:
```
docker-compose up -d
```
It doesn't work.  And then I remember I need to login to the container and run `pycsw_setup`:
```
docker exec -it pycsw bash
pycsw_setup
exit
```
What is the best way to avoid this manual step and get automatic startup?
